---
- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Transfer the script
      copy: src=user-data-mount-mongo.sh dest=/home/ubuntu/user-data-mount-mongo.sh mode=0777
    - name: Execute the script
      command: sh /home/ubuntu/user-data-mount-mongo.sh
